export const projectdata = [
    {
        id: 'Featured',
        title: 'Featured',
        name: 'LaoSpicy',
        picture: 'assets/images/project-bg.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure ',
        tech: [""],
        url: '',
        GitHub: "https://github.com/AnthonyZhang220/qrcode-ordering",
    },
    {
        id: 'Project',
        title: 'Featured',
        name: 'LaoSpicy',
        picture: 'assets/images/project-bg.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco ',
        tech: [""],
        url: '',
        GitHub: "https://github.com/AnthonyZhang220/qrcode-ordering",
    },
    {
        id: 'Project',
        title: 'Featured',
        name: 'LaoMa Spicy Queue System',
        picture: 'assets/images/project-bg.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco ',
        tech: [""],
        url: '',
        GitHub: "https://github.com/AnthonyZhang220/qrcode-ordering",
    },
];