export const musicList = [
	{
		id: 1,
		title: "Ballade No.1 In G Minor, Op.23",
		source: "assets/audios/Ballade.mp3",
		cover: "assets/cover/pianist.jpg",
		artist: "Frédéric Chopin",
		performer: "Janusz Olejniczak",
	},
	{
		id: 2,
		title: "海の見える街  〜魔女の宅急便",
		source: "assets/audios/jazz.mp3",
		cover: "assets/cover/jazz.jpg",
		artist: "Joe Hisaishi",
		performer: "Cafe Music BGM channel",
	},
	{
		id: 3,
		title: "Kass' Theme",
		source: "assets/audios/Kass.mp3",
		cover: "assets/cover/zelda.jpg",
		artist: "The Legend of Zelda: Breath of the Wild OST",
		performer: "LEGEND OF ZELDA",
	},
	// {
	//     id: "4",
	// 	title: "",
	// 	source: "",
	// 	cover: "",
	// 	artist: "",
	//     performer: '',
	// },
	// {
	//     id: "5",
	// 	title: "",
	// 	source: "",
	// 	cover: "",
	// 	artist: "",
	//     performer: '',
	// },
];
