export const musicList = [
	{
		id: "1",
		title: "Ballade No.1 In G Minor, Op.23",
		source: "assets/audios/Ballade.mp3",
		cover: "assets/cover/pianist.jpg",
		artist: "Frédéric Chopin",
        performer: 'Janusz Olejniczak',
	},
	{
        id: "2",
		title: "海が見える街",
		source: "assets/audios/jazz.mp3",
		cover: "assets/cover/jazz.jpg",
		artist: "Joe Hisaishi",
        performer: 'Cafe Music BGM channel',
	},
	// {
    //     id: "3",
	// 	title: "",
	// 	source: "",
	// 	cover: "",
	// 	artist: "",
    //     performer: '',
	// },
	// {
    //     id: "4",
	// 	title: "",
	// 	source: "",
	// 	cover: "",
	// 	artist: "",
    //     performer: '',
	// },
	// {
    //     id: "5",
	// 	title: "",
	// 	source: "",
	// 	cover: "",
	// 	artist: "",
    //     performer: '',
	// },
];
